server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka9000.com:9000/eureka/, http://eureka9001.com:9001/eureka/
spring:
  application:
    name: vher-consumer

#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000
logging:
  level:
    org.example.cloud.api: debug
