server:
  port: 8001
spring:
  application:
    name: eureka-client-hr-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8010/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
      prefer-ip-address: true
        #Eureka客户端向服务端发送心跳的时间间隔.单位为秒(默认30 秒)
      lease-renewal-interval-in-seconds: 1
        #Eureka服务端在收到最后一次心跳等待时间上限.单位为秒(默认90 秒),超时将剔除服务
      lease-expiration-duration-in-seconds: 2


